# Generated by Django 5.1 on 2024-08-30 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('model', models.CharField(max_length=255)),
                ('engine_model', models.CharField(max_length=255)),
                ('engine_serial_number', models.CharField(max_length=255)),
                ('transmission_model', models.CharField(max_length=255)),
                ('transmission_serial_number', models.CharField(max_length=255)),
                ('drive_axle_model', models.CharField(max_length=255)),
                ('drive_axle_serial_number', models.CharField(max_length=255)),
                ('steer_axle_model', models.CharField(max_length=255)),
                ('steer_axle_serial_number', models.CharField(max_length=255)),
                ('supply_contract', models.CharField(max_length=255)),
                ('shipment_date', models.DateField()),
                ('consignee', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('configuration', models.TextField()),
                ('client', models.CharField(max_length=255)),
                ('service_company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField()),
                ('operating_hours', models.IntegerField()),
                ('failure_unit', models.CharField(max_length=255)),
                ('failure_description', models.TextField()),
                ('recovery_method', models.CharField(max_length=255)),
                ('used_spare_parts', models.TextField()),
                ('recovery_date', models.DateField()),
                ('downtime', models.IntegerField()),
                ('service_company', models.CharField(max_length=255)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.machine')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=255)),
                ('maintenance_date', models.DateField()),
                ('operating_hours', models.IntegerField()),
                ('order_number', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('organization', models.CharField(max_length=255)),
                ('service_company', models.CharField(max_length=255)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.machine')),
            ],
        ),
    ]
