# Generated by Django 5.1 on 2024-08-30 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveAxleModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FailureUnitReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethodReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompanyReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SteerAxleModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalMaintenanceTypeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='technicalmaintenance',
            name='organization',
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='configuration',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_axle_models', to='silant_app.driveaxlemodelreference'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_models', to='silant_app.enginemodelreference'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='failure_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_units', to='silant_app.failureunitreference'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_models', to='silant_app.machinemodelreference'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='recovery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_methods', to='silant_app.recoverymethodreference'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_service_companies', to='silant_app.servicecompanyreference'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_companies', to='silant_app.servicecompanyreference'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_service_companies', to='silant_app.servicecompanyreference'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steer_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steer_axle_models', to='silant_app.steeraxlemodelreference'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_types', to='silant_app.technicalmaintenancetypereference'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmission_models', to='silant_app.transmissionmodelreference'),
        ),
    ]
